name: githab-actions
on: push
jobs:
        my-job:
                runs-on: macos-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: setup-python
                        uses: actions/setup-python@v2
                        - name: install1
                        run:  pip install poetry
                        - name: install2
                        run: make install
                        - name: run-linter
                        run:  make lint